version: '3.8'

services:
  app:
    image: backstage:latest
    environment:
      POSTGRES_SERVICE_HOST: db
      POSTGRES_SERVICE_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "7007:7007"
  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
volumes:
  postgres-data:
